# Generated by Django 5.2.12 on 2026-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="boa_account",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Bank of Abyssinia Account",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cbe_account",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="CBE Account Number"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telebirr_account",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telebirr Number"
            ),
        ),
    ]
