# Generated by Django 5.2.12 on 2026-06-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_boa_account_customuser_cbe_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Is Approved/Active"),
        ),
    ]
