# Generated by Django 5.2.12 on 2026-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
