# Generated by Django 5.2.12 on 2026-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_worker_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
