# Generated by Django 5.2.12 on 2026-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_ticket_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
