# Generated by Django 5.2.12 on 2026-09-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_customuser_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelebirrOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_trade_no", models.CharField(max_length=64, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("prepay_id", models.CharField(blank=True, default="", max_length=128)),
                ("to_pay_url", models.URLField(blank=True, default="", max_length=500)),
                ("trans_id", models.CharField(blank=True, default="", max_length=64)),
                ("notify_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
